### ISSUE TITLE
Partially Broken; No longer Sends Messages or Shows Pictures

### ISSUE THREAD

**Issue by acjones8** [dosdude1/discord-lite#15]
I noticed today when firing up Discord Lite that it seems like something's changed on DIscord's end, it no longer shows any profile pictures for users or servers, and I can't send messages through the client anymore (though it still lists all of the severs, and it still shows messages sent by other users while you're in a channel). Curious if anyone else has this issue?

**Comment by Jairbear73** [comment]
I had this once when I hadn’t used it for a few weeks, but I quit and opened it again and it was fine.

Sent from my PC via Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 11.

From: Alex ***@***.***>
Sent: Friday, 13 May 2022 12:51
To: ***@***.***>
Cc: ***@***.***>
Subject: [dosdude1/discord-lite] Partially Broken; No longer Sends Messages or Shows Pictures (Issue #15)


I noticed today when firing up Discord Lite that it seems like something's changed on DIscord's end, it no longer shows any profile pictures for users or servers, and I can't send messages through the client anymore (though it still lists all of the severs, and it still shows messages sent by other users while you're in a channel). Curious if anyone else has this issue?
