### ISSUE TITLE
Two-factor isn't presented to the user

### ISSUE THREAD

**Issue by VisualisationExpo** [dosdude1/discord-lite#16]
Two-factor doesn't work with Discord Lite.

After entering my password in the password text field I get a message saying "This field is required" 

Regular Discord app and website and two-factor works fine and has for a while.

I'm on an Intel iMac late 2015.
![dlite](https://user-images.githubusercontent.com/86615159/168808556-4872459d-5951-4ddc-b28c-a5753fdb2b58.jpg)
![dlite-about](https://user-images.githubusercontent.com/86615159/168809029-76f5edf9-a06f-4b89-afd3-ff431e0c63d0.jpg)

**Comment by dosdude1** [comment]
There's some weird issue that happens where it randomly decides to clear the password input field. Try using the "Log In" button to submit the info, that helps in some cases.

**Comment by VisualisationExpo** [comment]
Yea, that's odd. For the login to work I can't leave the password field un-highlighted - once I leave the password field and the password is left as being not highlighted - and I then click login, nothing happens. Once I leave the password as highlighted then I receive the following window without being able to press anywhere that results in anything.
![nope](https://user-images.githubusercontent.com/86615159/170085929-809dd624-0a20-44fd-903e-dc7b32ed01e7.jpg)

**Comment by VisualisationExpo** [comment]
I read that by building the app from source would help the CAPTHCA issue - it did.. even got the two factor authentication working on macOS Monterey.
