### ISSUE TITLE
Cant login / cannot connect to discord server

### ISSUE THREAD

**Issue by jackseverity** [dosdude1/discord-lite#18]
Hi there.  As of today I haven't been able to login to discord.
when launched today no servers were loading.
I deleted the plist file as other have tried which logged me out and I was able to put in my account info but it would just sit there spinning.
I then deleted discord lite and re downloaded latest release from gitub in case mine was out of date.
After I put my info in the freshly downloaded discord lite i get 
_"Error"
"Could not connect tot he discord server. please check your net connection"_
Net is working fine, Id say discord has changed something.
Hope you can get it sorted mate. incredible app. use it pretty much daily. 
Tried version 0.1.4 & 0.1.5
450mhz G4 cube Tiger

**Comment by charlie-hotel** [comment]
Can confirm, this has stopped working for me on all machines as well.

**Comment by pingy717** [comment]
having this issue on my 2009 macbook pro running snow leopard, hope this gets fixed.

**Comment by dosdude1** [comment]
Unfortunately, Discord has just recently completely disabled anything older than TLS 1.2 on their server, and I'm not exactly sure what I'm going to do about it at this time... I'll see if I can find some sort of other WebSockets and HTTP library that doesn't rely on CFNetwork, and implement that. In the meantime, though, it is possible to utilize a proxy on another more modern machine to work around the issue.

**Comment by charlie-hotel** [comment]
Unfortunately I'm running my machines using oldssl-proxy docker container and while they can successfully log in, not much happens after that :(

**Comment by acjones8** [comment]
Can confirm, I use an oldssl-proxy container as well, and I haven't had luck getting it to work either - nothing seems to load. Funnily enough, I suspect this might have been behind the mysterious no icons problem I had a while back, as I that was around the same time I started tinkering with the proxy.

I wonder if it's the custom certificate that oldssl-proxy generates that's the issue?

**Comment by dosdude1** [comment]
There's a separate proxy configuration that has to be set for the WebSocket (as the system proxy settings only affect the HTTP side, which uses NSURLConnection). The thing is, while I can set the proxy settings of CFNetwork for the WebSocket, NSURLConnection does not have any way to set the proxy settings outside of the system proxy setting... So I'm trying to find the least clunky way of implementing custom proxy settings at the moment.

**Comment by dosdude1** [comment]
I added a preferences window to allow you to set the proxy configuration for the WebSocket... Unfortunately I was having a lot of trouble getting a custom proxy configuration working for the HTTP requests. For now, you will need to set the system proxy configuration using System Preferences as well.

![Picture_13](https://user-images.githubusercontent.com/23435713/186331902-6ef5e798-c29f-4b8a-9bba-1657f7ebf66b.png)

**Comment by dremin** [comment]
If you don't mind, what solution are you using as a SOCKS proxy for websockets? I've been using `oldssl-proxy` for HTTPS, but it's not via SOCKS. I've tried a few solutions without success, so I would appreciate to hear what has worked for you.

**Comment by dosdude1** [comment]
I've been using Charles Proxy on another machine, which works well for this. SOCKS is required for WebSockets, it won't work with an HTTP(S) proxy.

**Comment by acjones8** [comment]
Are there any free alternatives to Charles Proxy that are known to work? I tried it with [Shiny Socks](https://github.com/jgaa/shinysocks), a small standalone server, but even though curl and Firefox work with it fine, Discord Lite doesn't. I'm guessing this is because Shiny Socks doesn't handle the TLS part correctly (Discord Lite connects to gateway.discord.gg, downloads 8 bytes worth of info, and then doesn't do anything further...)

**Comment by dosdude1** [comment]
Probably doesn't support WebSockets... Try this: https://github.com/ticky/mitmproxy-oldssl

Haven't tried it myself, but mitmproxy supposedly supports SOCKS5 and WebSockets.

**Comment by Lana-chan** [comment]
is there any possibility of using [crypto ancienne](https://github.com/classilla/cryanc) as a library for the program to be built against to do its own TLS1.3?

**Comment by Useydess** [comment]
so im currently trying to get discord lite to work on os x leopard and im confused on the socks proxy server settings, is there any good videos on setting one up or anyone here who knows how to set one up

**Comment by acjones8** [comment]
Thanks for the new update! I gave it a try and everything works great, can log in and chat and everything.

**Comment by dosdude1** [comment]
A new implementation has been completed, replacing CFNetwork with the latest version of Curl and OpenSSL libs, fully resolving all SSL issues.
