### ISSUE TITLE
Captcha not working in 0.1.6

### ISSUE THREAD

**Issue by dremin** [dosdude1/discord-lite#19]
Hi, when running 0.1.6 under Leopard, the captcha web view doesn't seem to load. The following message appears a few times in the Console:
`8/24/22 12:13:30 AM Discord Lite[225] *** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (WebView) `

If I roll back to 0.1.3, the web view appears correctly.

**Comment by dosdude1** [comment]
Should now be fixed with the latest release.

**Comment by dremin** [comment]
Can confirm, it is. Thanks!

**Comment by leency** [comment]
Not fixed. 036
https://ibb.co/2nhgtdg
