### ISSUE TITLE
ARM support for M series Macs

### ISSUE THREAD

**Issue by jacksongoode** [dosdude1/discord-lite#27]
Just wanted to add an issue so interest can be tracked.

**Comment by dosdude1** [comment]
I do plan on it (and have successfully compiled and have had it working natively on ARM), but the process of adding the ARM slice is very convoluted. Once I get a good process down, I'll start releasing builds with native ARM support.

**Comment by dosdude1** [comment]
Native ARM support has now been added.

**Comment by jacksongoode** [comment]
Thanks!
