### ISSUE TITLE
2FA Errors

### ISSUE THREAD

**Issue by GeekLucanis** [dosdude1/discord-lite#41]
The client will not accept any of the 2FA codes, and will also log me out of all instances of Discord on every attempt. 
I am running 10.5.8 with brew and all xcode, on a 11,2 PowerMac G5

**Comment by eimi-codes** [comment]
Same error on PPC Tiger 10.4.11

**Comment by dosdude1** [comment]
Currently being worked on. The cause if the issue has been found, and I'll have it fixed very soon.

**Comment by dosdude1** [comment]
Should now be resolved with latest release. Once confirmed, I'll close the issue.

**Comment by GeekLucanis** [comment]
Issue resolved.
